theme: jekyll-theme-leap-day

title: ?'s Blog
description: ?の部落格

show_downloads: true

github:
  zip_url: https://kirarachan.github.io/about
  tar_url: https://kirarachan.github.io/indexes
  repository_url: https://kirarachan.github.io/
